{{ if .Values.alternativeHostNames }}
{{- $fullName := include "bahnhofsAbfahrten.fullname" . -}}
{{- range .Values.alternativeHostNames }}
{{- $altName := print $fullName "-app-" . | replace "." "-" -}}
{{- $altDocName := print $fullName "-docs-" . | replace "." "-" -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $altName }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: 'https://{{$.Values.hostName}}$request_uri'
spec:
  rules:
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
    - host: www.{{ . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
  tls:
    - hosts:
        - {{ . }}
        - www.{{ . }}
      secretName: {{ $altName }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $altDocName }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: 'https://docs.{{$.Values.hostName}}$request_uri'
spec:
  rules:
    - host: docs.{{ . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: docs-{{ $fullName }}
                port:
                  name: http
    - host: www.docs.{{ . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: docs-{{ $fullName }}
                port:
                  name: http
  tls:
    - hosts:
        - docs.{{ . }}
        - www.docs.{{ . }}
      secretName: {{ $altName }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $altName }}
spec:
  secretName: {{ $altName }}
  issuerRef:
    name: http-issuer
    kind: ClusterIssuer
  dnsNames:
    - {{ . }}
    - www.{{ . }}
    - docs.{{ . }}
    - www.docs.{{ . }}
---
{{- end }}
{{ end }}
