apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: '{{ include "bahn-expert.fullname" . }}'
spec:
  maxUnavailable: {{ .Values.disruption.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{ include "bahn-expert.name" . }}'
      app.kubernetes.io/instance: '{{ .Release.Name }}'
