env:
  - name: ENVIRONMENT
    value: beta
  - name: PLAUSIBLE_URL
    value: https://beta.bahn.expert/api/event

hostName: beta.bahn.expert
alternativeHostNames:
  - beta.abfahrten.in
  - beta.marudor.de

replicaCount: 1
