env:
  - name: ENVIRONMENT
    value: beta
  - name: PLAUSIBLE_URL
    value: https://beta.marudor.de/api/event

hostName: beta.marudor.de
alternativeHostNames:
  - beta.abfahrten.in
  - beta.bahn.expert

replicaCount: 1
