env:
  - name: ENVIRONMENT
    value: production
  - name: LOGGLY_TOKEN
    valueFrom:
      secretKeyRef:
        name: bahnhofs-abfahrten-config
        key: loggly_token
        optional: true

hostName: bahn.expert
alternativeHostNames:
  - abfahrten.in
  - marudor.de

replicaCount: 10

disruption:
  maxUnavailable: 4

resources:
  requests:
    memory: '1Gi'
    cpu: '500m'
