env:
  - name: ENVIRONMENT
    value: production

hostName: bahn.expert
alternativeHostNames:
  - abfahrten.in
  - marudor.de

replicaCount: 5

disruption:
  maxUnavailable: 4

resources:
  requests:
    memory: '768Mi'
    cpu: '400m'
  limit:
    memory: '2Gi'
    cpu: '1'
