env:
  - name: ENVIRONMENT
    value: production

hostName: bahn.expert
alternativeHostNames:
  - abfahrten.in
  - marudor.de

replicaCount: 10

disruption:
  maxUnavailable: 4

resources:
  requests:
    memory: '1Gi'
    cpu: '500m'
