env:
  - name: ENVIRONMENT
    value: production

hostName: bahn.expert
alternativeHostNames:
  - abfahrten.in

replicaCount: 5

disruption:
  maxUnavailable: 4

resources:
  requests:
    memory: '768Mi'
    cpu: '600m'
